### ISSUE TITLE
Dockerfile doesn't work.

### ISSUE THREAD

**Issue by samwightt** [nicholascioli/webassignment#1]
Unable to get the dockerfile to work from the assignment. The IP address given from the command doesn't have anything running on port 3000.

**Comment by nicholascioli** [comment]
Interestingly enough, you would need to bind the container's port to a port on your local machine using either the -P flag to allow your computer to randomly assign a local port mapping, or the -p flag followed by the syntax LOCAL_PORT:CONTAINER_PORT.

So an example of the command necessary to get the stock Dockerfile to work after building the image would be either:

```bash
docker run -it --rm -p 3000:3000 IMAGE_NAME
docker run -it --rm -P IMAGE_NAME
```

I'll look over your pull request now and see if it would simplify things.

**Comment by samwightt** [comment]
Ah yep, forgot about that! That definitely would simplify things.

**Comment by nicholascioli** [comment]
I have never used Docker compose before, so this is good learning experience for me. Could I ask that you simplify the changes a bit so that I don't have a mix of tabs and spaces throughout the codebase?

**Comment by samwightt** [comment]
For sure! I’ll reformat the code and let you know when I’ve finished  :)

**Comment by nicholascioli** [comment]
Also, your docker-compose file in #2 seems to be trying to pass ./wait-for.sh directly to node. 

![Annotation 2020-04-16 102249](https://user-images.githubusercontent.com/1240491/79474727-5f785900-7fcc-11ea-9e47-14f843266189.png)

**Comment by samwightt** [comment]
Agh I may not have included that! That’s a script that just waits for the
mongo server to start up because `depends_on` just waits for the container
to start, not for mongo to be completely set up.

**Comment by samwightt** [comment]
Actually wait, it is included. Lemme get back to my desktop and see what’s going on.

**Comment by nicholascioli** [comment]
Figured it out: Windows doesn't have file permissions and so the shell script didn't have +x set. Run it with `sh wait-for.sh ...` instead.

This still won't completely fix it however as Windows git replaces line feed with carriage return line feed, which then causes sh to die. I'm trying to fix now.

**Comment by samwightt** [comment]
Gotcha, lemme know if you need me to do anything else!

**Comment by nicholascioli** [comment]
It seems as though imported documents do not appear when running the container. Running `db.HW6.count()` in a shell on the container returns 0.

Any idea why that is?

**Comment by samwightt** [comment]
What command did you use to log into the shell again? Having trouble logging in after running `docker-compose run db mongo`.

**Comment by nicholascioli** [comment]
I connected using the nodejs container.

Il gio 16 apr 2020, 16:46 Sam Wight <notifications@github.com> ha scritto:
